### ISSUE TITLE
ImportError: No module named component.hooks

### ISSUE THREAD

**Issue by Eveli** [plone-ve/plonethemes.suite#16]
Hi :) Later to install and run my Zope instance it's show me the follow error:

```
canaima@CU:~/plonethemes.suite$ bin/instance fg
2015-06-24 05:48:14 INFO ZServer HTTP server started at Wed Jun 24 05:48:14 2015
    Hostname: 0.0.0.0
    Port: 8081
2015-06-24 05:48:24 INFO collective.easyslider Installed slider easytemplate tag
2015-06-24 05:48:29 WARNING SecurityInfo Conflicting security declarations for "<AccessControl.SecurityInfo.ClassSecurityInfo object at 0x7f902b4cea50>"
2015-06-24 05:48:29 WARNING SecurityInfo Conflicting security declarations for "<AccessControl.SecurityInfo.ClassSecurityInfo object at 0x7f902b4cea50>"
2015-06-24 05:48:29 WARNING SecurityInfo Class "BlobWrapper" had conflicting security declarations
2015-06-24 05:48:29 WARNING SecurityInfo Conflicting security declarations for "<AccessControl.SecurityInfo.ClassSecurityInfo object at 0x7f902b4a3490>"
2015-06-24 05:48:29 WARNING SecurityInfo Conflicting security declarations for "<AccessControl.SecurityInfo.ClassSecurityInfo object at 0x7f902b4a3490>"
2015-06-24 05:48:29 WARNING SecurityInfo Class "BlobField" had conflicting security declarations
Traceback (most recent call last):
  File "/home/canaima/plonethemes.suite/parts/instance/bin/interpreter", line 447, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/home/canaima/plonethemes.suite/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
    run()
  File "/home/canaima/plonethemes.suite/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/run.py", line 22, in run
    starter.prepare()
  File "/home/canaima/plonethemes.suite/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/__init__.py", line 86, in prepare
    self.startZope()
  File "/home/canaima/plonethemes.suite/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/__init__.py", line 262, in startZope
    Zope2.startup()
  File "/home/canaima/plonethemes.suite/eggs/Zope2-2.13.22-py2.7.egg/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/home/canaima/plonethemes.suite/eggs/Zope2-2.13.22-py2.7.egg/Zope2/App/startup.py", line 118, in startup
    load_zcml()
  File "/home/canaima/plonethemes.suite/eggs/Zope2-2.13.22-py2.7.egg/Zope2/App/startup.py", line 52, in load_zcml
    load_site()
  File "/home/canaima/plonethemes.suite/eggs/Zope2-2.13.22-py2.7.egg/Zope2/App/zcml.py", line 46, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/home/canaima/plonethemes.suite/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 649, in file
    include(context, name, package)
  File "/home/canaima/plonethemes.suite/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/home/canaima/plonethemes.suite/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 352, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/canaima/plonethemes.suite/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/home/canaima/plonethemes.suite/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/home/canaima/plonethemes.suite/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/home/canaima/plonethemes.suite/eggs/Zope2-2.13.22-py2.7.egg/OFS/metaconfigure.py", line 46, in loadProducts
    xmlconfig.include(_context, zcml, package=product)
  File "/home/canaima/plonethemes.suite/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/home/canaima/plonethemes.suite/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 352, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/canaima/plonethemes.suite/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/home/canaima/plonethemes.suite/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/home/canaima/plonethemes.suite/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/home/canaima/plonethemes.suite/eggs/z3c.autoinclude-0.3.5-py2.7.egg/z3c/autoinclude/zcml.py", line 104, in includePluginsDirective
    includeZCMLGroup(_context, info, filename)
  File "/home/canaima/plonethemes.suite/eggs/z3c.autoinclude-0.3.5-py2.7.egg/z3c/autoinclude/zcml.py", line 30, in includeZCMLGroup
    include(_context, filename, includable_package)
  File "/home/canaima/plonethemes.suite/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/home/canaima/plonethemes.suite/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 352, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/canaima/plonethemes.suite/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/home/canaima/plonethemes.suite/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/home/canaima/plonethemes.suite/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/home/canaima/plonethemes.suite/eggs/grokcore.component-2.5-py2.7.egg/grokcore/component/zcml.py", line 57, in grokDirective
    do_grok(package.__name__, _context, extra_exclude=exclude)
  File "/home/canaima/plonethemes.suite/eggs/grokcore.component-2.5-py2.7.egg/grokcore/component/zcml.py", line 71, in do_grok
    config=config)
  File "/home/canaima/plonethemes.suite/eggs/martian-0.14-py2.7.egg/martian/core.py", line 203, in grok_dotted_name
    grok_package(module_info, grokker, **kw)
  File "/home/canaima/plonethemes.suite/eggs/martian-0.14-py2.7.egg/martian/core.py", line 208, in grok_package
    grok_package(sub_module_info, grokker, **kw)
  File "/home/canaima/plonethemes.suite/eggs/martian-0.14-py2.7.egg/martian/core.py", line 208, in grok_package
    grok_package(sub_module_info, grokker, **kw)
  File "/home/canaima/plonethemes.suite/eggs/martian-0.14-py2.7.egg/martian/core.py", line 206, in grok_package
    grok_module(module_info, grokker, **kw)
  File "/home/canaima/plonethemes.suite/eggs/martian-0.14-py2.7.egg/martian/core.py", line 211, in grok_module
    grokker.grok(module_info.dotted_name, module_info.getModule(),
  File "/home/canaima/plonethemes.suite/eggs/martian-0.14-py2.7.egg/martian/scan.py", line 141, in getModule
    self._module = resolve(self.dotted_name)
  File "/home/canaima/plonethemes.suite/eggs/martian-0.14-py2.7.egg/martian/scan.py", line 217, in resolve
    __import__(used)
  File "/home/canaima/plonethemes.suite/src/collective.megadrop/collective/megadrop/browser/viewlets.py", line 9, in <module>
    from zope.app.component.hooks import getSite
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/home/canaima/plonethemes.suite/parts/instance/etc/site.zcml", line 16.2-16.23
    ZopeXMLConfigurationError: File "/home/canaima/plonethemes.suite/eggs/Products.CMFPlone-4.3.6-py2.7.egg/Products/CMFPlone/configure.zcml", line 98.4-102.10
    ZopeXMLConfigurationError: File "/home/canaima/plonethemes.suite/src/collective.megadrop/collective/megadrop/configure.zcml", line 8.4-8.29
    ImportError: No module named component.hooks
```

This error was because collective.megadrop don't have support for Plone 4.3, I fixed this error and I pushed the solution into collective repository.

Then is needed update this configuration into ``theme.cfg`` file.

**Comment by macagua** [comment]
@Eveli ok thanks for you report. Please, update you fork repo and make a pull request ;-)

**Comment by macagua** [comment]
Done by @Eveli :-)
